using NUnit.Framework;
using System;
using FrontEnd;
using System.Collections.Immutable;
using System.Threading;

namespace FrontEnd // uses this namespace to access members internal to it (UI elements generated by XAML)
{
    [TestFixture]
    [Apartment(ApartmentState.STA)] // Proper WPF threading: https://stackoverflow.com/questions/2434067/how-to-run-unit-tests-in-stathread-mode
    public class CreditCardApplicantTests 
    {
        [SetUp]
        public void Setup()
        {
        }

        [Test(Author="K McEvaddy")]
        public void ApplicantTitleBelongsToTitleEnum()
        {
            // Arrange
            MainWindow mainWindow = new MainWindow();
            //~~ Get the list of all title values
            ImmutableList<string> titlesList = 
                Enum.GetNames(typeof(Titles)).ToImmutableList<string>();
            //~~ Get the value of the current
            string currentApplicantTitle = mainWindow.ApplicantData.Title.ToString();
            
            // Act, Assert
            Assert.That
            (
                titlesList.Contains(currentApplicantTitle)
            );
        }
    }
}
